### ISSUE TITLE
PyPy3 not found by tox

### ISSUE THREAD

**Issue by altendky** [actions/setup-python#151]
**Describe the bug**
In my nightly builds (with no recent changes) tox stopped finding PyPy3 on Windows.  I haven't had a chance to explore this yet but will certainly share when I do.

Last pass: https://github.com/pytest-dev/pytest-twisted/runs/1224277840?check_suite_focus=true
First fail: https://github.com/pytest-dev/pytest-twisted/runs/1229756319?check_suite_focus=true

CFFI updated from 1.14.0 to 1.14.2, but that doesn't seem likely to be related.  On the other hand there was an update from PyPy 7.3.1 to 7.3.2 between the passing and failing build.

```
3.6.9 (2ad108f17bdb, Apr 07 2020, 03:05:35)
[PyPy 7.3.1 with MSC v.1912 32 bit]
```
```
3.6.9 (d38cd66c14b8, Sep 23 2020, 08:02:17)
[PyPy 7.3.2 with MSC v.1927 32 bit]
```

<details> <summary>Full error</summary>

```
Run tox -v -e "pypy3-defaultreactor"
  tox -v -e "pypy3-defaultreactor"
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    PIP_NO_PYTHON_VERSION_WARNING: 1
    pythonLocation: C:\hostedtoolcache\windows\PyPy\3.6.9\x86
using tox.ini: D:\a\pytest-twisted\pytest-twisted\tox.ini (pid 3568)
using tox-3.20.0 from c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\__init__.py (pid 3568)
GLOB sdist-make: D:\a\pytest-twisted\pytest-twisted\setup.py
[2856] D:\a\pytest-twisted\pytest-twisted$ 'c:\hostedtoolcache\windows\pypy\3.6.9\x86\python.exe' setup.py sdist --formats=zip --dist-dir 'D:\a\pytest-twisted\pytest-twisted\.tox\dist' >.tox\log\GLOB-0.log
package .tmp\package\1\pytest-twisted-1.13.2.zip links to dist\pytest-twisted-1.13.2.zip (D:\a\pytest-twisted\pytest-twisted\.tox)
___________________________________ summary ___________________________________
ERROR:   pypy3-defaultreactor: undefined
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\interpreters\__init__.py", line 25, in get_executable
    return self.name2executable[envconfig.envname]
KeyError: 'pypy3-defaultreactor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\lib-python\3\runpy.py", line 196, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\lib-python\3\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\PyPy\3.6.9\x86\bin\tox.exe\__main__.py", line 7, in <module>
    sys.exit(cmdline())
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\session\__init__.py", line 44, in cmdline
    main(args)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\session\__init__.py", line 69, in main
    exit_code = session.runcommand()
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\session\__init__.py", line 197, in runcommand
    return self.subcommand_test()
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\session\__init__.py", line 225, in subcommand_test
    run_sequential(self.config, self.venv_dict)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\session\commands\run\sequential.py", line 9, in run_sequential
    if venv.setupenv():
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\venv.py", line 615, in setupenv
    with self.new_action("getenv", self.envconfig.envdir) as action:
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\venv.py", line 135, in new_action
    self.envconfig.envpython,
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\config\__init__.py", line 1032, in envpython
    return self.get_envpython()
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\config\__init__.py", line 1040, in get_envpython
    return self.envbindir.join(name)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\config\__init__.py", line 1027, in envbindir
    return self.get_envbindir()
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\config\__init__.py", line 1014, in get_envbindir
    isinstance(self.python_info, NoInterpreterInfo)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\config\__init__.py", line 1053, in python_info
    return self.config.interpreters.get_info(envconfig=self)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\interpreters\__init__.py", line 33, in get_info
    executable = self.get_executable(envconfig)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\interpreters\__init__.py", line 27, in get_executable
    exe = self.hook.tox_get_python_executable(envconfig=envconfig)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\interpreters\windows\__init__.py", line 14, in tox_get_python_executable
    spec, path = base_discover(envconfig)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\interpreters\common.py", line 17, in base_discover
    cur_spec = exe_spec(discover, envconfig.basepython)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\interpreters\via_path.py", line 38, in exe_spec
    info = get_python_info(python_exe)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\site-packages\tox\interpreters\via_path.py", line 66, in get_python_info
    universal_newlines=True,
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\lib-python\3\subprocess.py", line 744, in __init__
    restore_signals, start_new_session)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\lib-python\3\subprocess.py", line 1045, in _execute_child
    startupinfo)
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\lib_pypy\_winapi.py", line 321, in CreateProcess
    raise _WinError()
  File "c:\hostedtoolcache\windows\pypy\3.6.9\x86\lib_pypy\_winapi.py", line 30, in _WinError
    raise excep
OSError: [WinError 87] The parameter is incorrect
Error: Process completed with exit code 1.
```
</details>

**Which version of the action are you using?**

- [ ] `v1`
- [x] `v2`
- [ ] Some other tag (such as `v2.0.1` or `master`)

**Environment**
- [ ] self-hosted
- [ ] Linux
- [x] Windows
- [ ] Mac

windows-2019

**Python Versions**
PyPy 3

**Comment by csm10495** [comment]
Also seeing this here: https://github.com/csm10495/pytest-html/runs/1239943180?check_suite_focus=true

**Comment by altendky** [comment]
https://github.com/tox-dev/tox/issues/1704
https://foss.heptapod.net/pypy/pypy/-/issues/3331

**Comment by hugovk** [comment]
PyPy 7.3.3 has now been released with a fix. https://github.com/actions/setup-python/issues/163 is a request to add it to GHA.

**Comment by hugovk** [comment]
GHA now has PyPy 7.3.3: https://github.com/actions/setup-python/issues/163#issuecomment-739907048

Can this be closed?

**Comment by altendky** [comment]
Yep, thanks for the reminder.
