### ISSUE TITLE
No module named pip on Python 3.7

### ISSUE THREAD

**Issue by williamcroberts** [actions/setup-python#260]
**Description:**

No module named pip on Python 3.7:

```
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/hostedtoolcache/Python/3.7.12/x64/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/runner/work/tpm2-pytss/tpm2-pytss/setup.py'"'"'; __file__='"'"'/home/runner/work/tpm2-pytss/tpm2-pytss/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-uxpcl4jb
       cwd: /home/runner/work/tpm2-pytss/tpm2-pytss/
  Complete output (31 lines):
  /opt/hostedtoolcache/Python/3.7.12/x64/bin/python3: No module named pip
  Traceback (most recent call last):
    File "/tmp/pip-build-env-2v74rl5z/overlay/lib/python3.7/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
      subprocess.check_call(cmd)
    File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.7.12/x64/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp_fcj3907', '--quiet', 'asn1crypto']' returned non-zero exit status 1.
```

This was working 

Broken 3.7:
  - https://github.com/tpm2-software/tpm2-pytss/runs/3949742135?check_suite_focus=true

Working 3.7:
  - https://github.com/tpm2-software/tpm2-pytss/runs/3949697882?check_suite_focus=true

Empty Commit (broken 3.7):
  - https://github.com/tpm2-software/tpm2-pytss/runs/3954754734?check_suite_focus=true

I was concerned that all the breaks were on the "master" branch from the matrix, however it breaks on non-master too
  - https://github.com/tpm2-software/tpm2-pytss/runs/3954754785?check_suite_focus=true
   
**Action version:**
v2

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
Python 3.7

**Repro steps:**  
Broken 3.7:
  - https://github.com/tpm2-software/tpm2-pytss/runs/3949742135?check_suite_focus=true

Working 3.7:
  - https://github.com/tpm2-software/tpm2-pytss/runs/3949697882?check_suite_focus=true

Empty Commit (broken 3.7):
  - https://github.com/tpm2-software/tpm2-pytss/runs/3954754734?check_suite_focus=true

I was concerned that all the breaks were on the "master" branch from the matrix, however it breaks on non-master too
  - https://github.com/tpm2-software/tpm2-pytss/runs/3954754785?check_suite_focus=true

**Expected behavior:**
I expect pip install .[dev] to pass, or at least fail without the "No module named pip" error.

**Actual behavior:**
pip install fails with, "No module named pip"

**Comment by williamcroberts** [comment]
I also tried to disable pip517, but that doesn't work either;
```
Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages (57.4.0)
Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages (21.3)
+ python3 -m pip install --user -e '.[dev]' --no-use-pep517
Obtaining file:///home/runner/work/tpm2-pytss/tpm2-pytss
ERROR: Disabling PEP 517 processing is invalid: project specifies a build backend of setuptools.build_meta in pyproject.toml
```
