### ISSUE TITLE
Python 3.6 fails to setup

### ISSUE THREAD

**Issue by Andrew-Sheridan** [actions/setup-python#355]
**Description:**

The setup-python action fails for python 3.6. Other versions work (7 ,8 ,9 ,10).

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**

- 3.6 (tested w/ 3.6.14 and 3.6.15)
- the self hosted runner is based on `summerwind/actions-runner:latest`

**Repro steps:**  
A description with steps to reproduce the issue. If you have a public example or repo to share, please provide the link.
```yaml
---
name: test
on:
  workflow_dispatch:

jobs:
  test:
    name: 🧪 test / python ${{ matrix.python-version }}
    runs-on: [self-hosted]
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6.14, '3.7']
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
```

**Expected behavior:**
A description of what you expected to happen.

It sets up correctly

**Actual behavior:**
A description of what is actually happening.

It dies. Here are logs from the action:

```text
2022-03-16T19:45:34.3840755Z ##[group]Run actions/setup-python@v2
2022-03-16T19:45:34.3841197Z with:
2022-03-16T19:45:34.3841518Z   python-version: 3.6.14
2022-03-16T19:45:34.3842225Z   token: ***
2022-03-16T19:45:34.3842529Z ##[endgroup]
2022-03-16T19:45:34.6686433Z Version 3.6.14 was not found in the local cache
2022-03-16T19:45:35.0947796Z Version 3.6.14 is available for downloading
2022-03-16T19:45:35.0948760Z Download from "https://github.com/actions/python-versions/releases/download/3.6.14-113064/python-3.6.14-linux-20.04-x64.tar.gz"
2022-03-16T19:45:36.8208337Z Extract downloaded archive
2022-03-16T19:45:36.8602517Z [command]/usr/bin/tar xz --warning=no-unknown-keyword -C /runner/_work/_temp/f3616ac2-a060-4459-aa80-2bf9b1a5ba49 -f /runner/_work/_temp/16ba1877-59d2-49e5-b04c-ab64688683eb
2022-03-16T19:45:39.4422472Z Execute installation script
2022-03-16T19:45:39.4585392Z Check if Python hostedtoolcache folder exist...
2022-03-16T19:45:39.4586407Z Creating Python hostedtoolcache folder...
2022-03-16T19:45:39.4609201Z Create Python 3.6.14 folder
2022-03-16T19:45:39.4657455Z Copy Python binaries to hostedtoolcache folder
2022-03-16T19:45:40.0671333Z Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)
2022-03-16T19:45:40.0939333Z Upgrading PIP...
2022-03-16T19:45:43.2414135Z Looking in links: /tmp/tmpodahf6uu
2022-03-16T19:45:43.2423536Z Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages (40.6.2)
2022-03-16T19:45:43.2514677Z Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages (18.1)
2022-03-16T19:45:44.5200555Z ##[error]Exception:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 259, in run
    with self._build_session(options) as session:
  File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 76, in _build_session
    if options.cache_dir else None
  File "/opt/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not int
2022-03-16T19:45:44.5817205Z ##[error]The process '/usr/bin/bash' failed with exit code 2
```

**Comment by Andrew-Sheridan** [comment]
Looks like the error is occurring while pip is upgrading itself, but I'm not sure how to resolve it

**Comment by Andrew-Sheridan** [comment]
I just decided to drop support for 3.6 🤷🏻‍♂️

**Comment by drothlis** [comment]
> I just decided to drop support for 3.6 🤷🏻‍♂️

For those finding this via Google: You can still use GitHub Actions with Python 3.6; you just have to use `ubuntu-20.04` instead of `ubuntu-latest`.
